spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://39.107.25.139:3306/yuan?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    addresses: 39.107.25.139
    port: 5672
    username: guest
    password: guest
  redis:
#    host: 39.107.25.139
    port: 6379
    host: 127.0.0.1

#    这个配置是解决数据库的下划线字段和实例类的驼峰命名不匹配导致数据结果有误而设置为true。
#    修改日志格式
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
#org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.imooc.mall.dao.CategoryMapper.queryById
#报这个错的原因，未找到mapper.xml文件，需要添加如下路径。
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #    控制台Mybatis打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
#  设置session过期时间。
server:
  servlet:
    session:
      timeout: 120
